### ISSUE TITLE
开发大大，有原理图嘛

### ISSUE THREAD

**Issue by 1634514080** [future-Hu/pedometer#1]
开发大大，有原理图嘛，

**Comment by Sentaku1129** [comment]
# 51的还是MPU6050的？

## MPU6050原理图
![image](https://user-images.githubusercontent.com/71433417/216307624-06496d4f-254f-4cd1-b6f6-747aa8e565f4.png)

## 51的可以网上找一下，就是普中的，都差不多

**Comment by 1634514080** [comment]
> # 51的还是MPU6050的？

OKOK，感谢大大
